### ISSUE TITLE
[Feature Request]: Store and show port number

### ISSUE THREAD

**Issue by igorpecovnik** [armbian/configng#161]
### Which feature would you like to have?

Several software packages will have service running at particular ports and we need to show that information somehow in the menu it self. For example - Cockpit is using port 9090

![image](https://github.com/user-attachments/assets/1f6e1354-48bb-4995-b75a-e2ca57a5560f)

Perhaps M03 - Stop Cockpit service (http://IP_ADDDRESS:9090) ?

### Funding

- [ ] [I am willing to cover expenses](https://www.armbian.com/contact/)

**Comment by Tearran** [comment]
>NOTE:

The Cockpit installation sets up a MOTD, allowing us to retrieve service port information
```
cat /run/cockpit/motd | sed 's/Web console: //'
```

**Comment by igorpecovnik** [comment]
> The Cockpit installation sets up a MOTD

Yes, I have noticed that. Some do this, some not.
