### ISSUE TITLE
Check debian package structure

### ISSUE THREAD

**Issue by igorpecovnik** [armbian/configng#20]
debian.conf defines paths mapping, which can be different on Git then on filesystem. See if I set i right and adjust. When done, I'll enable automated import to nightly repository.

**Comment by Tearran** [comment]
As i understand.
all that is needed is 
- `configng/bin/* = /usr/bin/`
- `configng/lib/* = /usr/lib/`

Share folder at this stage is handled by [documents](https://github.com/armbian/configng/blob/main/lib/armbian-configng/documents.sh)  to overcome some naming conventions.

**Comment by igorpecovnik** [comment]
> As i understand.

Yes
