### ISSUE TITLE
[Bug]: Desktop installation fails for CLI image.

### ISSUE THREAD

**Issue by schmiedelm** [armbian/configng#225]
### What happened?

Running the Desktop installation from Software menu `Desktops     -  Desktop Environments` show black screen and after a few seconds. No matter which environment is chosen.

Error Message:

```
Failed to restart display-manager.service: Unit display-manager.service not found.
Failed to stop gdm3.service: Unit gdm3.service not loaded.
Failed to stop lightdm.service: Unit lightdm.service not loaded.
Failed to stop sddm.service: Unit sddm.service not loaded.
Failed to restart display-manager.service: Unit display-manager.service not found.
```

### How to reproduce?

Run an Image without Desktop environment CLI Image.

- log in as user
- run configng as root
- choose Software -> Desktops -> Gnome

### On which host OS are you running the build script and observing this problem?

Ubuntu 24.04 Noble

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by igorpecovnik** [comment]
Disabled. Need refactoring at build side.
