### ISSUE TITLE
Can't access HARDWARE config on OrangwPi Zero

### ISSUE THREAD

**Issue by wizbandit** [armbian/configng#255]
### What happened?

ls: cannot access '/*.dtbo': No such file or directory
ls: cannot access '/*.dtbo'Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
: No such file or directory
ls: cannot access '/*.dtbo': No such file or directory
Usage: grep [OPTION]... PATTERNS [FILE]...
Try 'grep --help' for more information.
Armbian Config: The Next Generation

How to make this tool even better?

### How to reproduce?

SYSTEM/Manage device tree overlays

### On which host OS are you running the build script and observing this problem?

Ubuntu 24.04 Noble

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by igorpecovnik** [comment]
Duplicate.
https://github.com/armbian/configng/issues/243
