### ISSUE TITLE
wlan0

### ISSUE THREAD

**Issue by Dedistyw** [armbian/configng#309]
### What happened?

i cant scan ap .
i cant set ip static for wlan , when connect to ap.

### How to reproduce?

in devica b860h

### On which host OS are you running the build script and observing this problem?

Ubuntu 24.04 Noble

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tearran** [comment]
@Dedistyw can you use
- `nmtui connect`
- `nmtui edit`

**Comment by Dedistyw** [comment]
Yes, i can edit and set ip static , thanks alot sir

Pada Min, 8 Des 2024, 09.45, Joey Turner ***@***.***> menulis:

**Comment by igorpecovnik** [comment]
Can you try again with latest version of armbian-config?

**Comment by Dedistyw** [comment]
Yes i've can set the ip static from nmtui, the cause nm is not installed ,
thanks alot

Pada Kam, 12 Des 2024, 03.26, Igor ***@***.***> menulis:
