### ISSUE TITLE
SOS

### ISSUE THREAD

**Issue by dimitry-ishenko** [armbian/configng#311]
@igorpecovnik @Tearran  and anyone else:

I am sorry, I've accidentally pushed to the wrong remote and nuked the following branches:
```
 - [deleted]         221-cannot-access-portainer-web-gui
 - [deleted]         259-task-replace-existing-keys-with-a-single-consistent-key-list
 - [deleted]         Tearran-patch-1
 - [deleted]         Tearran-patch-2
 - [deleted]         actions
 - [deleted]         add_cpu_freq
 - [deleted]         apt-mark
 - [deleted]         atuin
 - [deleted]         automation
 - [deleted]         gui-mouse
 - [deleted]         homepage
 - [deleted]         igor
 - [deleted]         improve-function
 - [deleted]         jellyseerr
 - [deleted]         netnames
 - [deleted]         nfsdfix
 - [deleted]         options_to_json
 - [deleted]         repository
 - [deleted]         sync
```

I am trying to figure out how to recover them. If you can, please push your branches back. Hopefully, I didn't screw anyone up. It doesn't usually happen to me... I am really sorry again.

**Comment by Tearran** [comment]
@dimitry-ishenko  I did something like that on the other config project once. IMO a happy accident, was nice to see it bar for a mi lol. Many of them do not need restored. As outdated or examples to concept.  

```
options_to_json
gui-mouse
Tearran-patch-1
259-task-replace-existing-keys-with-a-single-consistent-key-list
```

**Comment by dimitry-ishenko** [comment]
Thanks @Tearran. I've managed to restore them all. 😓 Feel free to nuke them if they are not needed. Sorry for all the noise. It's been a long day and then I decided to do some coding before going to bed... 🤯

**Comment by Tearran** [comment]
ooh, that would be good for https://github.com/armbian/configng/wiki

Think it would be nice to have some git-fu bits like that.

**Comment by igorpecovnik** [comment]
> It's been a long day and then I decided to do some coding before going to bed..

No worries, glad things were restored quickly and we are back in the game. And we learned something new.
