### ISSUE TITLE
Error while update && upgrade 

### ISSUE THREAD

**Issue by WesselPwa** [armbian/configng#316]
### What happened?

Err:1 https://github.armbian.com/configng stable/main arm64 armbian-config all 20241013-1817
  404  Not Found [IP: 185.199.110.153 443]
E: Failed to fetch https://github.armbian.com/configng/pool/main/a/armbian-config/armbian-config_20241013-1817_all.deb  404  Not Found [IP: 185.199.110.153 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

### How to reproduce?

apt update && apt upgrade

### On which host OS are you running the build script and observing this problem?

Debian 12 Bookworm

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by igorpecovnik** [comment]
This will eventually be auto-fixed, but we need to improve updating mechanism.

**Comment by igorpecovnik** [comment]
Fixed, works now.
