### ISSUE TITLE
Firmware - execute apt update and upgrade to update your system,

### ISSUE THREAD

**Issue by Tearran** [armbian/configng#32]
>armbian-config [#207](https://github.com/armbian/config/issues/207)
>Fails to run properly if executed from a non-graphical terminal session (e.g. sshpass)
sudo armbian-config main=System selection=Firmware

## What is the procedure to:
-  `                       │ │   Firmware  Update all packages and firmware                 │ │                            `
    -  `main=System selection=Firmware`? 

### how is normally this done width in the build community

- `./build some=commands`
- `apt update && upgrade`
- ` apt dist-upgrade`
-  `apt full-upgrade`

**Comment by igorpecovnik** [comment]
./build command SWITC1=yes SWITCH=test ...
