### ISSUE TITLE
[Bug]: kernel switch failed

### ISSUE THREAD

**Issue by EvilOlaf** [armbian/configng#337]
### What happened?

Tried to switch from `current` to `edge` kernel on OPi1+ (sunxi64 to say).
Did not survive reboot. Mounted the sdcard and for unknown reason the symlinks for /boot/Image and uInitrd were dead end.
Used `dpkg` to install an image and dtb package via `chroot` to fix it.

### How to reproduce?

Did not try to reproduce nor did any further investigation. Since that was my local dns my primary goal was to get it back online asap :grin

### On which host OS are you running the build script and observing this problem?

Debian 12 Bookworm

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EvilOlaf** [comment]
Go home, you're drunk lol

**Comment by igorpecovnik** [comment]
This was the problem in old builds ... Does this happens on fully upgraded armbian-config?

**Comment by EvilOlaf** [comment]
I freshly installed armbian-config before attempting since it wasn't installed.

**Comment by igorpecovnik** [comment]
When you install image, first upgrade of armbian-config adds repository, second is updating from this. Just make sure ... will add build date to the welcome screen soon.

**Comment by EvilOlaf** [comment]
Yeah I see. First upgrade indeed bumped to 25.2 trunk

**Comment by igorpecovnik** [comment]
https://github.com/armbian/configng/commit/023bc8dd291c42342cb567e9a3d1747fc502b308

**Comment by EvilOlaf** [comment]
Assuming it was fixed already and kernel switch failed due to outdated armbian-config package
