### ISSUE TITLE
[Bug]: Problem with bash trap handling

### ISSUE THREAD

**Issue by kjkuan** [armbian/configng#74]
### What happened?

FYI, given a curious look at the project source files, I found an issue with the use of `EXIT` trap here - https://github.com/armbian/configng/blob/80ceb1e6723b6a58ead1d17682b255581e9d5ca4/lib/bash-utility-master/src/file.sh#L23

When the function is used as documented, e.g.,
```bash
tmpfile=$(file::make_temp_file)
...  # then use $tmpfile here
```
`$tmpfile` would be deleted before it can be used.

The problem is that `$(...)` is its own sub process, so the `EXIT` trap set up in the function is triggered upon the end of the sub process, and the temporary file would be gone by the time the command substitution returns. The same problem exists with the [file::make_temp_dir](https://github.com/armbian/configng/blob/80ceb1e6723b6a58ead1d17682b255581e9d5ca4/lib/bash-utility-master/src/file.sh#L43) function, but worse, because the entire temporary might be deleted, which would lead to an error when trying to `cd` into it or when trying to create a file in it.

### How to reproduce?

It looks like the temp file functions are not actually used at all in the project, so it's just a potential bug, and this report is just FYI.

### On which host OS are you running the build script and observing this problem?

Ubuntu 24.04 Noble

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tearran** [comment]
>It looks like the temp file functions are not actually used at all in the project, so it's just a potential bug, and this report is just FYI.

Thank you, Bring up a good point. 

none of `configng/lib/bash-utility-master` files are actually being used at this point.
